export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CLEAR_LOCAL_STORAGE = "CLEAR_LOCAL_STORAGE";
export const LOGOUT = "LOGOUT";

export const CAMBIAR_PASSWORD_REQUEST = "CAMBIAR_PASSWORD_REQUEST";
export const CAMBIAR_PASSWORD_SUCCESS = "CAMBIAR_PASSWORD_SUCCESS";
export const CAMBIAR_PASSWORD_FAILURE = "CAMBIAR_PASSWORD_FAILURE";

export const REGISTRO_USUARIO_REQUEST = "REGISTRO_USUARIO_REQUEST";
export const REGISTRO_USUARIO_SUCCESS = "REGISTRO_USUARIO_SUCCESS";
export const REGISTRO_USUARIO_FAILURE = "REGISTRO_USUARIO_FAILURE";

export const LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";

export const UPDATE_USUARIO_REQUEST = "UPDATE_USUARIO_REQUEST";
export const UPDATE_USUARIO_SUCCESS = "UPDATE_USUARIO_SUCCESS";
export const UPDATE_USUARIO_FAILURE = "UPDATE_USUARIO_FAILURE";
